### Create,Shape,Reshape

In [1]:
import numpy as np
ones= np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [2]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
n=np.arange(12)
m=np.arange(3,21,3)
m

array([ 3,  6,  9, 12, 15, 18])

In [5]:
np.shape(n)

(12,)

In [7]:
twod=np.reshape(n,(3,4))

In [9]:
twod.size


12

In [10]:
twod.ndim

2

In [11]:
ones.ndim

1

### Set Data Type

In [14]:
twod.dtype

dtype('int64')

In [27]:
twod=twod.astype(np.int8)
twod.dtype

dtype('int8')

In [29]:
oned= np.arange(100,dtype=np.int8)
oned.dtype

dtype('int8')

### BroadCatsting

In [36]:
A1= np.array([[1,2,3],[4,5,6],[7,8,9]])
A2=np.ones(9).reshape((3,3))
A1+A2

array([[ 2.,  3.,  4.],
       [ 5.,  6.,  7.],
       [ 8.,  9., 10.]])

In [40]:
A3= np.ones(3)
A3.shape

(3,)

In [41]:
A3+A2

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

### Matrix Operation

In [42]:
A1.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [43]:
A2.diagonal()

array([1., 1., 1.])

In [44]:
A1@A2

array([[ 6.,  6.,  6.],
       [15., 15., 15.],
       [24., 24., 24.]])